# Taken from https://towardsdatascience.com/a-data-scientist-approach-running-postgres-sql-using-docker-1b978122e5e6
version: '2'
services:
  postgresql12:
    image: 'bitnami/postgresql:12'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data_12:/bitnami/postgresql12'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=pwd0123456789
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  postgresql_data_12:
    driver: local